import {NextIntlClientProvider, useMessages} from 'next-intl';

import './globals.css'
import { Montserrat } from 'next/font/google'
import { CartProvider } from '@/context/cartContext';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
} & { params: { locale: string } }) {
  const messages = useMessages();

  return (
    <html lang={locale}>

      <body className={montserrat.className}>
          <CartProvider>
        <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
          </NextIntlClientProvider>
          </CartProvider>
        </body>
    </html>
  )
}
